[build]
  publish = "dist"
  command = "npm run build"

[forms]
  settings = { formsTimeout = 60 }

# Headers de seguridad básicos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff" 
    X-XSS-Protection = "1; mode=block"